# Site settings
title: Working on something new
email: email@astritcepele.me
description: This is a portofolio, CV website that it is running totally at 0 costs.:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://astritcepele.me" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/astrit-%C3%A7epele/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
